### ISSUE TITLE
Problem with custom api host

### ISSUE THREAD

**Issue by Dynfy** [AndraxDev/speak-gpt#28]
When I try custom api host because my country banned chatgpt. But it only show this error:
a1.b: Cleartext HTTP traffic to localhost not permitted
	at j1.d.b(SourceFile:65)
	at j1.d.g(SourceFile:90)
	at j1.c.k(SourceFile:1)
	at s6.a.m(SourceFile:6)
	at h7.k0.run(SourceFile:100)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7211)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
Caused by: java.io.IOException: Cleartext HTTP traffic to localhost not permitted
	at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:485)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
	at d5.e.c(SourceFile:494)
	at c5.b.k(SourceFile:59)
	at s6.a.m(SourceFile:6)
	at h7.k0.run(SourceFile:108)
	at androidx.appcompat.widget.k.run(SourceFile:15)
	at m7.i.run(SourceFile:3)
	at m7.a.run(SourceFile:92)
What I am missing here?

**Comment by AndraxDev** [comment]
Which host do you want to set?

**Comment by AndraxDev** [comment]
To protect your privacy this app can not connect to localhost and non https servers. Make sure your connection is secure.

**Comment by AndraxDev** [comment]
Can you please soecify full URL that you are trying to pass to the SpeakGPT.

**Comment by AndraxDev** [comment]
You entered an invalid URL. URL must contain domain, port (optional), and path with params.

According to your URL you used aninvalid domain "relham". The domain must end with .extension (ex. .com, .org, etc). URL must have the following form: https://example.com/auth/...

**Comment by AndraxDev** [comment]
The answer is simple. Your URL is not valid. Please check the documentation for your API and try again.

**Comment by AndraxDev** [comment]
Using cleartext traffic is not secure. I recommend you to download source code and compile it itself. The public verion of app will not contain your change as it pose user privacy at risk. I take full responsibility for user privacy when I publish my app, but I take no responsibility for user derivations of app compiled from sources.

**Comment by AndraxDev** [comment]
Cleartext allows you to transfer data via http. I'm fully responsible for user privacy and I will never allow unencrypted connections. You can still put 1 line of code to AndroidManifest.xml and compile app from sources.

**Comment by AndraxDev** [comment]
I don't install any certificates to user device. App can be used out-of-box. But why can't you compile it yourself?

**Comment by AndraxDev** [comment]
Additionally I don't want to limit app functionality by cutting off some usefull features. The person who needs local llms can compile it itself. Additionally I'm not sure if OpenAI API allows custom local llms like llama, etc.

**Comment by AndraxDev** [comment]
1) Have you read what I'm written carefully? I said that I sign executable APK file with my signature before publishing. The're no word about self-signed cerificated for local servers.

2) If you compiled your version you can publish free and at no charge for non-commercial use. You can share on f-droid, but don't forget for attribution. Thanks!
