### ISSUE TITLE
3.13 crash in chat with image

### ISSUE THREAD

**Issue by AriesAlex** [AndraxDev/speak-gpt#77]
constantly crashes when using chat with image(3,8mb)

```
An app has been crashed and needs to be restarted.

===== BEGIN SYSTEM INFO =====
Android version: 13 (API 33 REL)
ROM version: 231129V1943
Device model: TECNO CK8n
Android device ID: 64d38445a9a34fe4
Installation ID: 47c90a05-5cfb-4626-be1a-7117f4597739
Effective time: 2024-04-10T21:55:53.794183Z
===== END SYSTEM INFO =====

===== BEGIN OF CRASH =====
java.lang.OutOfMemoryError: Failed to allocate a 7183160 byte allocation with 6078328 free bytes and 5935KB until OOM, target footprint 268435456, growth limit 268435456
 at java.lang.StringFactory.newStringFromBytes(Native Method)
 at java.lang.StringLatin1.newString(StringLatin1.java:738)
 at java.lang.StringBuilder.toString(StringBuilder.java:474)
 at gb.c.getView(Unknown Source:2088)
 at gb.d.getView(Unknown Source:220)
 at android.widget.AbsListView.obtainView(AbsListView.java:2404)
 at android.widget.ListView.measureHeightOfChildren(ListView.java:1417)
 at android.widget.ListView.onMeasure(ListView.java:1323)
 at android.view.View.measure(View.java:26563)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7093)
 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
 at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1204)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
 at android.view.View.measure(View.java:26563)
 at androidx.constraintlayout.widget.f.b(Unknown Source:499)
 at a4.f.x(Unknown Source:89)
 at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(Unknown Source:1398)
 at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(Unknown Source:523)
 at android.view.View.measure(View.java:26563)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7093)
 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
 at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1204)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
 at android.view.View.measure(View.java:26563)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7093)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
 at android.view.View.measure(View.java:26563)
 at com.google.android.material.bottomsheet.BottomSheetBehavior.onMeasureChild(Unknown Source:54)
 at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(Unknown Source:280)
 ```

**Comment by AndraxDev** [comment]
Fixed in 3.14
