### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Darkshadenl** [AndraxDev/speak-gpt#85]
I just installed this from the playstore and it crashes on start. 
I did see the privacy policy agreement screen before it crashed. 

```An app has been crashed and needs to be restarted.

===== BEGIN SYSTEM INFO =====
Android version: 12 (API 31 REL)
ROM version: G970FXXSGHWC1
Device model: SM-G970F
Android device ID: ae0de03db01e9c60
Installation ID: <Not assigned>
Effective time: 2024-04-19T15:40:53.572Z
===== END SYSTEM INFO =====

===== BEGIN OF CRASH =====
java.lang.RuntimeException: Unable to resume activity {org.teslasoft.assistant/org.teslasoft.assistant.ui.activities.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5312)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5351)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
	at p6.a.o(Unknown Source:51)
	at org.teslasoft.assistant.ui.fragments.tabs.ChatsListFragment.onResume(Unknown Source:25)
	at androidx.fragment.app.Fragment.performResume(Unknown Source:17)
	at androidx.fragment.app.a1.n(Unknown Source:124)
	at androidx.fragment.app.a1.k(Unknown Source:54)
	at androidx.fragment.app.t0.E(Unknown Source:61)
	at androidx.fragment.app.t0.o(Unknown Source:35)
	at androidx.fragment.app.b0.onResumeFragments(Unknown Source:23)
	at androidx.fragment.app.b0.onPostResume(Unknown Source:3)
	at android.app.Activity.performResume(Activity.java:8466)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5282)
	... 13 more

===== END OF CRASH =====```

**Comment by AndraxDev** [comment]
Fixed in release 3.19. Usually it takes 1-2 business days before release get published on Play Store.
