### ISSUE TITLE
Crash: when exiting during generation

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [AndraxDev/speak-gpt#97]
When using the assistant window, if the LLM is currently talking and I press Exit, I often (but not always!) get a crash (the crash log can be found below).

I was planning to open a feature request to ask for the the ability to interrupt the generation : UI suggestion would be by pressing the "microphone" or "send" button in their "currently generating" state.

The reason for adding this was primarily that since we can now edit and delete messages to me it makes sense to not have to wait for a whole generation to end for modifying the course of the conversation. But adding this feature might perhaps also solve the current issue because pressing Exit could then call the "stop generating" function before exiting.

```
An app has been crashed and needs to be restarted.

===== BEGIN SYSTEM INFO =====
Android version: 14 (API 34 REL)
ROM version: REDACTED
App version: 3.21 (321)
Device model: REDACTED
Android device ID: REDACTED
Installation ID: REDACTED
Effective time: 2024-04-27TREDACTED
===== END SYSTEM INFO =====

===== BEGIN OF CRASH =====
java.lang.IllegalStateException: Fragment x{7a00422} (68198783-d7a8-460b-a2b9-143546a20e65) not attached to an activity.
	at androidx.fragment.app.Fragment.requireActivity(Unknown Source:17)
	at kb.x.u(Unknown Source:10)
	at kb.x.h(Unknown Source:922)
	at kb.h.k(Unknown Source:13)
	at t8.a.h(Unknown Source:5)
	at j9.k0.run(Unknown Source:109)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
	Suppressed: n9.e: [p1{Cancelling}@ede406e, Dispatchers.Main]

===== END OF CRASH =====
```

**Comment by AndraxDev** [comment]
- Now this bug is fixed
- You can cancel response generation by clicking loading bar with cross inside.
